---
title: "Water Levels at Mono Lake"
description: |
  In my very first R class in Fall 2020, I made a highly customized graph showing changes in water level at Mono Lake in CA since 1850. Here's how I made it!
author:
  - name: Mukta Kelkar
    url: {}
date: 03-13-2021
output:
  distill::distill_article:
    self_contained: false
    code_folding: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
```

## Step 1: Read in and wrangle data

```{r read in and clean data, message = FALSE, warning=FALSE}
# Read in data
mono_lake <- read.csv(("mono_lake_annual_levels.csv"), skip = 5)

# Clean up data formatting
mono_lake_clean <- mono_lake %>% 
  clean_names() %>%                        #change column names to lowercase_snake_case
  select(year, lake_level_feet_above_sea_level, stable_level, vertical_change) %>%   #keep relevant variables
  mutate(land_bridge = 6377) %>% 
  mutate(shrimp_decrease = 6360) %>% 
  mutate(acute = 6350)

# Create a data frame with annotation info for horizontal lines on the graph
annotation_lines <- data.frame(
  x = c(2000, 2000, 2000, 2000),
  y = c(6392, 6377, 6360, 6350),
  label = c("Stable Water Level", "Land Bridge", "Food Limit Starts", "Acute Food Limits")
)

# Create a data frame with annotation info for points on the graph
annotation_points <- data.frame(
  x = c(1958, 1986),
  y = c(6423, 6384),
  label = c("LADWP diverts water", "Court ruling")
)
  
```

## Step 2: Create Visualization



```{r final data visualization, echo = FALSE, message = FALSE, warning = FALSE}
mono_lake_clean %>% 
  ggplot(aes(x = year)) +
  #geom_point(aes(y = lake_level_feet_above_sea_level), color = "deepskyblue1", size = 2.5, alpha = .5) +
  geom_line(aes(y = lake_level_feet_above_sea_level),  #insert line for lake level
            color = "deepskyblue4",
            size = 1) +
  annotate(geom = "point", x = 1941, y = 6417,  #add point for when LADWP started diverting water
           size = 4,
           color = "darkblue") +
  annotate(geom = "point", x = 1983, y = 6378.60,         #add a point for when CA Sumpreme court ruled in favor of Mono Lake Committee
           size = 4,
           color = "darkblue") +
  geom_ribbon(aes(ymin = -Inf,                    #fill in area below lake level line
                ymax = lake_level_feet_above_sea_level),
              fill = "deepskyblue3",
              alpha = .3) +
  geom_line(aes(y = stable_level),           #add a line for where the stable water level is
            color = "grey10",
            size = .7) +
  geom_line(aes(y = land_bridge),            #add a line for where the water receeds below a land bridge
            color = "darkgoldenrod",
            size = 0.7) +
  geom_line (aes(y = shrimp_decrease),        #add a line for where brine shrimp population starts decreasing
             color = "deeppink3",
             size = 0.7) +
  geom_line(aes(y = acute),                   #add a line for where brine shrimp population decrease has acute effects
            color = "darkorchid3",
            size = 0.7) +
  geom_label(data = annotation_lines, aes(x = x, y = y, label = label),   #add text for labels for two data points
             size = 3.5, color = "chocolate3", fontface = "bold") +
  geom_text(data = annotation_points, aes(x = x, y = y, label = label),      #add text for labels for horizontal lines representing key water levels
             size = 3.5, color = "black", fontface = "bold", angle = 10) +
  labs(x = "Year",              #add labels
       y = "Feet Above Sea Level",
       title = "Change in Water Level at Mono Lake",
       caption = "Figure 1: Mono Lake water levels meaured from 1850 to 2017.",
       subtitle = "Mono County, CA (Kootzaduka’a Territory)") +
  theme_classic() +
  theme(axis.text = element_text(size = 10),    #change font sizes
        axis.title = element_text(size = 12),
        plot.title = element_text(size = 14))

```



Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


